NAME = main

SRC_DIR = ./src/
SRC_NAME = main.c fourth.c 
SRC = $(addprefix $(SRC_DIR),$(SRC_NAME))

OBJ_DIR = ./dir/
OBJ_NAME = $(SRC_NAME:.c=.o)
OBJ = $(addprefix $(OBJ_DIR),$(OBJ_NAME))

CC = gcc
CFLAGS = -Wall -Werror -Wextra
